name: Unit Test and documentation

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest nltk matplotlib
      - name: Test with pytest
        run: pytest --verbose
      - name: Product html in Sphinx
        run: |
          pip install sphinx scikit-learn scipy sphinx_rtd_theme
          cd docs
          make html
      - name: Run ghp-import
        run: | 
            ghp-import -n docs/_build/html
              